#!/bin/sh

#taking the input for the filname
buildFile=$1
buildFile_without_extension="${buildFile%.*}"

#script for creating .exe for .cpp file 

mkdir -p builds

g++ $buildFile -o "builds/$buildFile_without_extension"

if [ $? -eq 0 ]; then
	./builds/"$buildFile_without_extension"
fi

